### ISSUE TITLE
TypeCache deadlock when loading assemblies in a specific order & dependency set

### ISSUE THREAD

**Issue by g-un--** [Catel/Catel#1120]
### Steps to reproduce

1. Create the following solution

    Lib A with two types: AB and AC and with B, C as lib references

    ``namespace A  { public class AB : B.B { } }``
    
    ``namespace A  { public class AC : C.C { } }``

    Lib B with one type: B

    ``namespace B { public class B {  } } ``

    Lib C with one type: C

    ``namespace C { public class C {  } } ``

    Console App: TypeCacheDeadLock with A as lib reference and with the following Program.cs : 
```
     class Program
     {
        static void Main(string[] args)
        {
            Catel.Reflection.TypeCache.InitializeTypes();
            Task.WaitAll(LoadAB(), LoadAC());
            Console.WriteLine("done");
            Console.ReadLine();
        }

        static Task LoadAC()
        {
            return Task.Run(() =>
            {
                var type = Type.GetType("A.AC, A, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");
                Console.WriteLine($"loaded type: {type.FullName}");
            });
        }

        static Task LoadAB()
        {
            return Task.Run(() =>
            {
                var type = Type.GetType("A.AB, A, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");
                Console.WriteLine($"loaded type: {type.FullName}");
            });
        }
    }
```
2. Run TypeCacheDeadLock console app

    .NET version: 4.5.2, 4.6
    Catel.Core: 4.5.4, 5.1.0

### Expected behaviour

Should not deadlock

### Actual behaviour

Deadlock

**Comment by GeertvanHorrik** [comment]
@alexfdezsauco please create unit tests. Once that is done, I'll look into the core issue.

**Comment by alexfdezsauco** [comment]
Implemented at https://github.com/Catel/Catel/tree/feature/1120

**Comment by g-un--** [comment]
@alexfdezsauco Please add reference to A, and check that types loaded are not null

**Comment by alexfdezsauco** [comment]
I will, but the current test actually checks the existence of the deadlock.

**Comment by alexfdezsauco** [comment]
Done

**Comment by g-un--** [comment]
Thank you @alexfdezsauco ! But "A" reference is still missing from Catel.Test.NET45 or the output folder for A, B, C should be the same used for Catel.Test.NET45. Now the loaded types are null, and the test is failing because of that. It should fail because of the timeout from Task.Wait.

**Comment by alexfdezsauco** [comment]
Sorry, my mistake. Just fixed.

**Comment by GeertvanHorrik** [comment]
Thanks, I expect to have time to look into this today.

**Comment by szogun1987** [comment]
OK. So problem is caused by calling GetTypesOfAssembly inside of OnAssemblyLoaded, it contains call of Initialize Method. That contains lock instead of MOnitor.TryEnter call.
Additionally AssemblyLoaded event is raised even if assembly wasn't initialized but only added to queue. Please ensure that it is OK (maybe it should be delayed).
I propose solution in attachment (currently I don't have VS 2017 and I had to downgrade some pieces of code on my local Catel copy).

[TypeCache.zip](https://github.com/Catel/Catel/files/1278401/TypeCache.zip)

**Comment by GeertvanHorrik** [comment]
@szogun1987 thanks for doing the research, we really appreciate this. I was sidetracked by other things, but expect to look into this on Monday.

**Comment by GeertvanHorrik** [comment]
Looks like it has been fixed 👍 

Will merge this to the develop branch and release a new (unstable) version.

**Comment by mpartipilo** [comment]
I am running into this (or very similar) issue when I use a SplashScreen Image. Removing the SplashScreen avoids the race condition.

**Comment by GeertvanHorrik** [comment]
@mpartipilo if you can provide a small repro, we might be able to look into it.
